# Generated by Django 4.1.3 on 2023-03-25 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
