# Generated by Django 4.1.3 on 2023-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0002_user_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="userlogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.TextField()),
            ],
        ),
    ]
