# Generated by Django 4.1.3 on 2023-03-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0003_userlogin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userlogin",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="userID",
        ),
    ]
