# Generated by Django 4.1.3 on 2023-03-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0005_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="course",
        ),
    ]
