# Generated by Django 4.1.3 on 2023-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0007_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="id",
        ),
        migrations.AlterField(
            model_name="course",
            name="coursecode",
            field=models.CharField(
                max_length=9, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
