# Generated by Django 4.1.3 on 2023-03-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0008_remove_course_id_alter_course_coursecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.TextField(default=""),
        ),
    ]
