# Generated by Django 4.1.3 on 2023-03-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0009_course_professor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_taught",
                to="drfapp.user",
            ),
        ),
    ]
