# Generated by Django 4.1.3 on 2023-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0011_remove_course_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.TextField(default=""),
        ),
    ]
