# Generated by Django 4.1.3 on 2023-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0014_course_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coursecode",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
