# Generated by Django 4.1.3 on 2023-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0016_alter_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="logo",
            field=models.CharField(default="", max_length=2),
        ),
    ]
