# Generated by Django 4.1.3 on 2023-03-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0018_user_userlogo_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yourmessages",
                to="drfapp.user",
            ),
        ),
    ]
