# Generated by Django 4.1.3 on 2023-03-30 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0019_alter_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.AddField(
            model_name="message",
            name="msgID",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
