# Generated by Django 4.1.3 on 2023-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0021_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="sender",
        ),
        migrations.AlterField(
            model_name="video",
            name="caption",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="videos/%y"),
        ),
    ]
