# Generated by Django 4.1.3 on 2023-04-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0022_remove_video_sender_alter_video_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.BinaryField(),
        ),
    ]
