# Generated by Django 4.1.3 on 2023-04-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0023_alter_video_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="video_file",
        ),
    ]
