# Generated by Django 4.1.3 on 2023-04-01 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0025_alter_video_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="assignment",
            fields=[
                ("file", models.FileField(upload_to="")),
                ("caption", models.CharField(max_length=100)),
                ("instruction", models.TextField()),
                ("uploadedtime", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                (
                    "assignmentID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("maxmarks", models.CharField(max_length=5)),
                (
                    "sentcourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="drfapp.course",
                    ),
                ),
            ],
        ),
    ]
