# Generated by Django 4.1.3 on 2023-04-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0026_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="uploadedtime",
        ),
    ]
