# Generated by Django 4.1.3 on 2023-04-01 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0027_remove_assignment_uploadedtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="solution",
            fields=[
                ("file", models.FileField(upload_to="")),
                ("senttime", models.DateTimeField()),
                (
                    "solutionID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sentassignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="givensolutions",
                        to="drfapp.assignment",
                    ),
                ),
                (
                    "sentuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="drfapp.user",
                    ),
                ),
            ],
        ),
    ]
