# Generated by Django 4.1.3 on 2023-04-02 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0030_grades"),
    ]

    operations = [
        migrations.CreateModel(
            name="grade",
            fields=[
                ("score", models.CharField(max_length=5)),
                ("review", models.TextField()),
                (
                    "gradeID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "TA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_solutions",
                        to="drfapp.user",
                    ),
                ),
                (
                    "soln",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="drfapp.solution",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="grades",
        ),
    ]
